### ISSUE TITLE
Read in rda-file doesn't work in use_dictionary_skeleton()

### ISSUE THREAD

**Issue by sebastian-loos** [openwashdata/openwashdata#12]
Hey @mbannert 

I wanted to update the dictionary with the changed variable names for the cbssuitabilityhaiti package and wanted to use your `use_dictionary_skeleton()` function. 

But when I run it, it gives me an error from [this line](https://github.com/openwashdata/openwashdata/blob/cc8225d2d128eca7ad88c6d68b6082a04ecf582f/R/use_dictionary.R#L37C5-L37C54):
`Error in readRDS(file.path(data_path, d)) : unknown input format`

I see that you are using the `readRDS()` function. `use_data()`, the function we use to save the data sets does save theme as ".rda" files in the `data` directory. Could that be the reason for the error?

I couldn't find a function that reads in rda-files simillar to the `readRDS()`. Do you have any ideas how to make it work?

It may also be a Windows problem. @mianzg and @larnsce have you tried it out?

**Comment by mbannert** [comment]
Yes, .Rds is a different format than .Rda. I prefer the serialized .Rds because GitHub sometimes corrupts .Rda files. But if use_data goes another route I'll have to think about finding a way to switch or to support both. 

Thanks for the pointer, I'll work on this.
